version: '3.7'

services:
  database:
    image: postgres:15.1-alpine
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=db
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=db
    networks:
      - task-manager
  # cache:
  backend:
    image: task-manager_api
    build: 
      dockerfile: ./docker/Dockerfile
      context: ./task-manager
    environment:
      - IS_DOCKER=true
      - APP_PORT=8080
      - SSL_PORT=8443
      - SWAGGER_PATH=docs
      - TOKEN_EXPIRATION=1h
      - DB_PORT=5432
      - DB_HOST=database
      - DB_USER=db
      - DB_PASSWORD=db
      - DB_NAME=db
    ports:
      - "8443:8443"
      - "8080:8080"
    networks:
      - task-manager
    depends_on:
      - database
    volumes:
      - task-vol:/app
  # frontend:

networks:
  task-manager:
    driver: bridge
volumes:
  task-vol:
    driver: local